const LOG_PARSER_NEW_GAME = 'LOG_PARSER_NEW_GAME';
const LOG_PARSER_PLAYER_CONNECTED = 'LOG_PARSER_PLAYER_CONNECTED';
const LOG_PARSER_PLAYER_DAMAGED = 'LOG_PARSER_PLAYER_DAMAGED';
const LOG_PARSER_PLAYER_DIED = 'LOG_PARSER_PLAYER_DIED';
const LOG_PARSER_PLAYER_REVIVE = 'LOG_PARSER_PLAYER_REVIVE';
const LOG_PARSER_PLAYER_WOUNDED = 'LOG_PARSER_PLAYER_WOUNDED';
const LOG_PARSER_SERVER_TICK_RATE = 'LOG_PARSER_SERVER_TICK_RATE';

export {
  LOG_PARSER_NEW_GAME,
  LOG_PARSER_PLAYER_CONNECTED,
  LOG_PARSER_PLAYER_DAMAGED,
  LOG_PARSER_PLAYER_DIED,
  LOG_PARSER_PLAYER_REVIVE,
  LOG_PARSER_PLAYER_WOUNDED,
  LOG_PARSER_SERVER_TICK_RATE
};
